pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t dhawalepallavi186/coit-backend1 .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
            steps {
               sh 'docker push dhawalepallavi186/coit-backend1'
            }
    }
}
}
